[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "./target/release/mubert-node"
args = ["--arweave-secret-key-path=.ignored/GvMBM9iXAQBRPKzhNxEPgqPay31IxXB1_865SpY6xrA.json"]
#args = ["--arweave-secret-key-path=path_to_test_arweave_wallet.json"]