[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000

[parachains.collator]
name = "charlie"
rpc_port = 9944
command = "./target/release/mubert-node"
#args = ["--arweave-secret-key-path=path_to_test_arweave_wallet.json"]