
//! Autogenerated weights for `pallet_ip_onchain`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.1.0
//! DATE: 2025-07-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! CPU: `13th Gen Intel(R) Core(TM) i7-13700HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/mubert-runtime/mubert_runtime.wasm
// --pallet
// pallet_ip_onchain
// --extrinsic
// 
// --template
// ./pallets/benchmarking/frame-weight-template.hbs
// --output
// ./pallets/pallet-ip-onchain/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ip_onchain`.
pub trait WeightInfo {
	fn create_author() -> Weight;
	fn edit_author() -> Weight;
	fn create_authority() -> Weight;
	fn edit_authority() -> Weight;
	fn create_entity() -> Weight;
	fn edit_entity() -> Weight;
	fn create_account_access() -> Weight;
	fn edit_account_access() -> Weight;
	fn call_toggle_nfts_support() -> Weight;
}

/// Weights for `pallet_ip_onchain` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NextAuthorId` (r:1 w:1)
	/// Proof: `IPOnchain::NextAuthorId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authors` (r:1 w:1)
	/// Proof: `IPOnchain::Authors` (`max_values`: None, `max_size`: Some(216), added: 2691, mode: `MaxEncodedLen`)
	fn create_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `207`
		//  Estimated: `4687`
		// Minimum execution time: 12_179_000 picoseconds.
		Weight::from_parts(13_224_000, 4687)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authors` (r:1 w:1)
	/// Proof: `IPOnchain::Authors` (`max_values`: None, `max_size`: Some(216), added: 2691, mode: `MaxEncodedLen`)
	fn edit_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `291`
		//  Estimated: `4687`
		// Minimum execution time: 12_863_000 picoseconds.
		Weight::from_parts(13_458_000, 4687)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NextAuthorityId` (r:1 w:1)
	/// Proof: `IPOnchain::NextAuthorityId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authorities` (r:1 w:1)
	/// Proof: `IPOnchain::Authorities` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NftsSupport` (r:1 w:0)
	/// Proof: `IPOnchain::NftsSupport` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:1)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn create_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `207`
		//  Estimated: `4687`
		// Minimum execution time: 19_932_000 picoseconds.
		Weight::from_parts(21_560_000, 4687)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:0)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authorities` (r:1 w:1)
	/// Proof: `IPOnchain::Authorities` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NftsSupport` (r:1 w:0)
	/// Proof: `IPOnchain::NftsSupport` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn edit_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354`
		//  Estimated: `4687`
		// Minimum execution time: 19_021_000 picoseconds.
		Weight::from_parts(19_627_000, 4687)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:0)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authorities` (r:1 w:0)
	/// Proof: `IPOnchain::Authorities` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Item` (r:1 w:1)
	/// Proof: `NFTs::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Collection` (r:1 w:1)
	/// Proof: `NFTs::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::CollectionConfigOf` (r:1 w:0)
	/// Proof: `NFTs::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::ItemConfigOf` (r:1 w:1)
	/// Proof: `NFTs::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NextEntityId` (r:1 w:1)
	/// Proof: `IPOnchain::NextEntityId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Entities` (r:1 w:1)
	/// Proof: `IPOnchain::Entities` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Account` (r:0 w:1)
	/// Proof: `NFTs::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	fn create_entity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `776`
		//  Estimated: `4687`
		// Minimum execution time: 56_260_000 picoseconds.
		Weight::from_parts(60_453_000, 4687)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Entities` (r:1 w:1)
	/// Proof: `IPOnchain::Entities` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:0)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authorities` (r:1 w:0)
	/// Proof: `IPOnchain::Authorities` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Item` (r:1 w:1)
	/// Proof: `NFTs::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Collection` (r:1 w:1)
	/// Proof: `NFTs::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::CollectionConfigOf` (r:1 w:0)
	/// Proof: `NFTs::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::ItemConfigOf` (r:1 w:1)
	/// Proof: `NFTs::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Account` (r:0 w:1)
	/// Proof: `NFTs::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	fn edit_entity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `840`
		//  Estimated: `4687`
		// Minimum execution time: 54_776_000 picoseconds.
		Weight::from_parts(56_929_000, 4687)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:2 w:1)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn create_account_access() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `6092`
		// Minimum execution time: 16_684_000 picoseconds.
		Weight::from_parts(17_732_000, 6092)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:1)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn edit_account_access() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `4687`
		// Minimum execution time: 14_877_000 picoseconds.
		Weight::from_parts(15_916_000, 4687)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `IPOnchain::NftsSupport` (r:1 w:1)
	/// Proof: `IPOnchain::NftsSupport` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn call_toggle_nfts_support() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `1486`
		// Minimum execution time: 4_594_000 picoseconds.
		Weight::from_parts(4_772_000, 1486)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NextAuthorId` (r:1 w:1)
	/// Proof: `IPOnchain::NextAuthorId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authors` (r:1 w:1)
	/// Proof: `IPOnchain::Authors` (`max_values`: None, `max_size`: Some(216), added: 2691, mode: `MaxEncodedLen`)
	fn create_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `207`
		//  Estimated: `4687`
		// Minimum execution time: 12_179_000 picoseconds.
		Weight::from_parts(13_224_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authors` (r:1 w:1)
	/// Proof: `IPOnchain::Authors` (`max_values`: None, `max_size`: Some(216), added: 2691, mode: `MaxEncodedLen`)
	fn edit_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `291`
		//  Estimated: `4687`
		// Minimum execution time: 12_863_000 picoseconds.
		Weight::from_parts(13_458_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NextAuthorityId` (r:1 w:1)
	/// Proof: `IPOnchain::NextAuthorityId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authorities` (r:1 w:1)
	/// Proof: `IPOnchain::Authorities` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NftsSupport` (r:1 w:0)
	/// Proof: `IPOnchain::NftsSupport` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:1)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn create_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `207`
		//  Estimated: `4687`
		// Minimum execution time: 19_932_000 picoseconds.
		Weight::from_parts(21_560_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:0)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authorities` (r:1 w:1)
	/// Proof: `IPOnchain::Authorities` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NftsSupport` (r:1 w:0)
	/// Proof: `IPOnchain::NftsSupport` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn edit_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `354`
		//  Estimated: `4687`
		// Minimum execution time: 19_021_000 picoseconds.
		Weight::from_parts(19_627_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:0)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authorities` (r:1 w:0)
	/// Proof: `IPOnchain::Authorities` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Item` (r:1 w:1)
	/// Proof: `NFTs::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Collection` (r:1 w:1)
	/// Proof: `NFTs::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::CollectionConfigOf` (r:1 w:0)
	/// Proof: `NFTs::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::ItemConfigOf` (r:1 w:1)
	/// Proof: `NFTs::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::NextEntityId` (r:1 w:1)
	/// Proof: `IPOnchain::NextEntityId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Entities` (r:1 w:1)
	/// Proof: `IPOnchain::Entities` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Account` (r:0 w:1)
	/// Proof: `NFTs::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	fn create_entity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `776`
		//  Estimated: `4687`
		// Minimum execution time: 56_260_000 picoseconds.
		Weight::from_parts(60_453_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Entities` (r:1 w:1)
	/// Proof: `IPOnchain::Entities` (`max_values`: None, `max_size`: Some(624), added: 3099, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:0)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::Authorities` (r:1 w:0)
	/// Proof: `IPOnchain::Authorities` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Item` (r:1 w:1)
	/// Proof: `NFTs::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Collection` (r:1 w:1)
	/// Proof: `NFTs::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::CollectionConfigOf` (r:1 w:0)
	/// Proof: `NFTs::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::ItemConfigOf` (r:1 w:1)
	/// Proof: `NFTs::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `NFTs::Account` (r:0 w:1)
	/// Proof: `NFTs::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	fn edit_entity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `840`
		//  Estimated: `4687`
		// Minimum execution time: 54_776_000 picoseconds.
		Weight::from_parts(56_929_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:2 w:1)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn create_account_access() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `6092`
		// Minimum execution time: 16_684_000 picoseconds.
		Weight::from_parts(17_732_000, 6092)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Membership::Members` (r:1 w:0)
	/// Proof: `Membership::Members` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
	/// Storage: `IPOnchain::AuthoritiesAccess` (r:1 w:1)
	/// Proof: `IPOnchain::AuthoritiesAccess` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn edit_account_access() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `343`
		//  Estimated: `4687`
		// Minimum execution time: 14_877_000 picoseconds.
		Weight::from_parts(15_916_000, 4687)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `IPOnchain::NftsSupport` (r:1 w:1)
	/// Proof: `IPOnchain::NftsSupport` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn call_toggle_nfts_support() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `1486`
		// Minimum execution time: 4_594_000 picoseconds.
		Weight::from_parts(4_772_000, 1486)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
